[default]
description = "Default permissions for the plugin: allows starting/stopping the camera preview and taking a picture."
permissions = ["allow-start-preview", "allow-stop-preview", "allow-take-picture"]
